language: java
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "hoijui-github"
    token:
      secure: ${SONAR_TOKEN}

jdk:
# Only test one JDK to save energy
#  - oraclejdk8
#  - oraclejdk11
  - openjdk8
#  - openjdk11

script:
# NOTE JaCoCo is used to have code coverage, the agent has to be activated
# NOTE The SonarCube Community Edition (free plan) only allows branch "master".
  - mvnExtra=""; if [ $TRAVIS_BRANCH = "master" ]; then mvnExtra="sonar:sonar"; fi; mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package $mvnExtra

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

env:
  global:
    secure: vWu9+stct7B2rRVP5EfSLbQEDWPchqnR2l1O0KeWhkiCCd6wZHsx8UQtbDpetsuBpNqBUrTn1ayFwVNsBfgaBZczl3sBh56jKp4iE5ufvxoXIx9b9HJHcEsy40PiP5mOLHnTOzGsdg6lE/26hR4O8PD/4YQr9HKsUxE6dUg4gYxesOh4IPbjWBQ3zvde8dw+gCvhNbD6+agZRmj6v5Ce/UayG9O+lovwuPds2hXZKX3n7VJmUxB7Rxm5Ab1x2h+l3Fsb4mIJR0Y5KGn/3G56Q+Eyt52qwNlSNO/KwIHx5uKSdN57q+K2Pdh+y+pw54POQwoZmtCwckMGAElXNkAQkoffSKR+q0VW41Tfl5B9IstS//m9n2ohCviMTJS2PUHM+pRxTQ8RrYodaqKqmaG4YD+OHdr7brn7tx7+3srB742fdyUWXmx3I3Waz8yJXGcKwCInl8Mrs0qWlMRfFWh9AHSb5UmtEQjDhrEubjZnBYYQBvU6K93SRV6HkGYf3Ea7MS8CBwGrPIb3H3kYPOgNZRYDuLXxksUOz+V5ffRIQCEcAlXmVcdB7OM6HFEPIVYgoIKQAFFTR5iBWXT9AvQiO4CBDKy74OrdcJSdT6FLL1G7CmjFXtgpngv1VR5MK/LnWSUpd24GXMMVCb4vS0jCjyrFAk+vbC6UFulEoskg98Y=
